lab50:
    windows:
        - editor
        - readme
        - terminal
    file:
        - Student.java
        - LayoutType.java
        - ListContainer.java
        - ArrayAdapter.java 
        - AdapterTest.java