lab50:
    windows:
        - editor
        - readme
        - terminal
    files: 
        - !exclude "*"
        - !include Activity.java
        - !include Callback.java
        - !include LongRunningTask.java
        - !include InterfaceTest.java