lab50:
  windows:
    - editor
    - readme
    - terminal
  files:
    - !exclude "*"
    - !include EnumTest.java
    - !include ConstantTest.java
    - !include StaticTest.java
    - !include AccessTest.java
    - !include Student.java