lab50:
    windows:
        - editor
        - readme
        - terminal
    files:
        - !exclude "*"
        - !include Student.java
        - !include Printer.java
        - !include ArrayAdapter.java 
        - !include AdapterTest.java
