lab50:
    windows:
        - editor
        - readme
        - terminal
    files: 
        - !exclude "*"
        - !include SomeClass.class
        - !include SomeClass$A.class
        - !include SomeClass$B.class
        - !include SomeClass$C.class
        - !include ExceptionTest.java
        - !include RandomExceptions.java