lab50:
    windows:
        - editor
        - readme
        - terminal
    files: 
        - !exclude "*"
        - !include ExceptionTest.java
        - !include ExceptionTest2.java
        - !include SomeClass.class